### ISSUE TITLE
the project's paper?

### ISSUE THREAD

**Issue by ShoulinWen** [haastregt/occlusion_tracking#2]
I am very interested in this project, can you provide the relevant papers published by your project for reading and studying? Thank you so much

**Comment by haastregt** [comment]
Hi! The paper was published by ICRA 2024: [IEEE Xplore](https://ieeexplore.ieee.org/document/10610904)

Also, this work was for my masters thesis which can be found here (and might contain additional details if necessary): [DiVa portal](https://kth.diva-portal.org/smash/record.jsf?aq2=%5B%5B%5D%5D&c=34&af=%5B%5D&searchType=LIST_LATEST&sortOrder2=title_sort_asc&query=&language=no&pid=diva2%3A1792999&aq=%5B%5B%5D%5D&sf=all&aqe=%5B%5D&sortOrder=author_sort_asc&onlyFullText=false&noOfRows=50&dswid=7137)

Great to hear that you are interested in the project, if there is anything else I can help with feel free to contact me!
